[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "hf2 elf"

rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabi"
