[package]
name = "cloud"
version = "0.1.0"
edition = "2018"
authors = [
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Ulf Lilleengen <lulf@redhat.com>"
]
description = "Example using operating system networking"
keywords = ["std", "networking", "cloud"]

[dependencies]
#pem-parser = "0.1.1"
log = "0.4"
env_logger = "0.8"
drogue-device = { path = "../../../device", features = ["log", "std", "tls"] }
embedded-tls = { version = "0.9.0", default-features = false, features = ["async", "log"]}
static_cell = "1"
#drogue-tls = {path = "../../../../drogue-tls", default-features = false, features = ["async", "defmt"]}

embassy-time = { version = "0.1.0", default-features = false, features = ["std"] }
embassy-executor = { version = "0.1.0", default-features = false, features = ["std", "integrated-timers"] }
rand = "0.8"
cfg-if = "1.0.0"

embedded-hal = { version = "0.2.4", features = ["unproven"] }
embedded-nal-async = "0.2.0"
embedded-io = { version = "0.3", features = ["futures"] }
drogue-temperature = { path = "../../apps/temperature", features = ["log", "tls"] }
futures = { version = "0.3.17", features = ["async-await"] }
async-io = "1.6.0"
