[package]
name = "browser"
version = "0.1.0"
authors = ["Ulf Lilleengen <lulf@redhat.com>"]
edition = "2018"
description = "WebAssembly using Drogue Device"
keywords = ["wasm"]

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
embedded-hal = { version = "0.2", features = ["unproven"] }
wasm-logger = "0.2.0"
log = "0.4"

drogue-device = { path = "../../../device", features = ["log"], default-features = false }
drogue-wasm = {git = "https://github.com/drogue-iot/drogue-wasm.git", branch = "main" }
embassy = { version = "0.1.0", default-features = false, features = ["wasm", "executor-agnostic"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "0d67ceb066f7b6d3b0163eaa3688b0499439a21c" }

#embassy = { path = "../../../../../embassy/embassy" }
