[package]
name = "browser"
version = "0.1.0"
authors = ["Ulf Lilleengen <lulf@redhat.com>"]
edition = "2018"
description = "WebAssembly using Drogue Device"
keywords = ["wasm"]

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
embedded-hal = { version = "0.2", features = ["unproven"] }
wasm-logger = "0.2.0"
log = "0.4"

drogue-device = { path = "../../../device", features = ["log"], default-features = false }
web-embedded-hal = "0.1.0"
embassy = { version = "0.1.0", default-features = false, features = ["wasm", "executor-agnostic", "nightly", "unstable-traits"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "77c7d8f31b89d13117a7294842d60f02950fdd23" }

#embassy = { path = "../../../../../embassy/embassy" }
