[package]
name = "browser"
version = "0.1.0"
authors = ["Ulf Lilleengen <lulf@redhat.com>"]
edition = "2018"
description = "WebAssembly using Drogue Device"
keywords = ["wasm"]

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
embedded-hal = { version = "0.2", features = ["unproven"] }
wasm-logger = "0.2.0"
log = "0.4"

drogue-device = { path = "../../../device", features = ["log", "actors"], default-features = false }
web-embedded-hal = "0.1.0"
embassy-executor = { version = "0.1.0", default-features = false, features = ["wasm", "nightly"] }
ector = { version = "0.1.0", default-features = false }
static_cell = "1"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "99284b830455dde9cd91091e2c1f4dda92936f51" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git", rev = "99284b830455dde9cd91091e2c1f4dda92936f51" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "99284b830455dde9cd91091e2c1f4dda92936f51" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "99284b830455dde9cd91091e2c1f4dda92936f51" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "99284b830455dde9cd91091e2c1f4dda92936f51" }
ector = { git = "https://github.com/drogue-iot/ector.git", rev = "cacee7281933a29549fe17a9ddafd2eefc58f768" }

#embassy-executor = { path = "../../../../../embassy/embassy" }
