[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"

]
edition = "2018"
name = "blinky"
version = "0.1.0"
description = "Raspberry Pi Pico Blinky"
keywords = ["rp", "rpi", "pico", "blinky", "basic"]

[workspace]

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }
drogue-device = { path = "../../../../device", features = ["defmt", "defmt-info"], default-features = false }
atomic-polyfill = { version = "0.1.1" }
embedded-hal = { version = "0.2.4", features = ["unproven"] }
rp2040-pac = { version = "0.1.4", features = ["rt"] }

cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }

embassy = { version = "0.1.0", default-features = false }
embassy-rp = { version = "0.1.0", default-features = false }

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "d9e2d176256ef4959c1ba60893ea361363d480d3" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy.git", rev = "d9e2d176256ef4959c1ba60893ea361363d480d3" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "d9e2d176256ef4959c1ba60893ea361363d480d3" }

#embassy = { path = "../../../../../embassy/embassy" }
#embassy-rp = { path = "../../../../../embassy/embassy-stm32" }
#embassy-hal-common = { path = "../../../../../embassy/embassy-hal-common" }