[package]
name = "drogue-device"
version = "0.1.0"
authors = ["Bob McWhirter <bmcwhirt@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.heapless]
version = "0.5.6"

[dependencies.cortex-m]
version = "0.6.0"

[dependencies.log]
version = "0.4.13"

[dependencies.embedded-hal]
version = "0.2.4"
features = ["unproven"]

[dependencies.stm32l4xx-hal]
path = "../stm32l4xx-hal"
features = ["stm32l4x5", "rt"]
optional = true

# ----------------------------------------
# embedded_time dependencies
# ----------------------------------------

[dependencies.num]
version = "0.3.0"
default-features = false

[features]
stm32l4xx = [ "stm32l4xx-hal" ]

