[workspace]
members = [
    "device",
    "apps/wifi",
    "macros",
    "xtask",
]
resolver = "2"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "675172f9816a41792d53ba9dcd33ad3592e94eb8" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "675172f9816a41792d53ba9dcd33ad3592e94eb8" }
embassy-lora = { git = "https://github.com/embassy-rs/embassy.git", rev = "675172f9816a41792d53ba9dcd33ad3592e94eb8" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "675172f9816a41792d53ba9dcd33ad3592e94eb8" }

# embassy = { path = "../../../../../embassy/embassy" }
# embassy-stm32 = { path = "../../../../../embassy/embassy-stm32" }
# embassy-hal-common = { path = "../../../../../embassy/embassy-hal-common" }
