[workspace]
members = [
    "device",
    "apps/wifi",
    "macros",
    "xtask",
]
resolver = "2"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "9fec833015579cca5f1b398745cac7ad08245f0c" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "9fec833015579cca5f1b398745cac7ad08245f0c" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "9fec833015579cca5f1b398745cac7ad08245f0c" }

# embassy = { path = "../../../../../embassy/embassy" }
# embassy-stm32 = { path = "../../../../../embassy/embassy-stm32" }
# embassy-hal-common = { path = "../../../../../embassy/embassy-hal-common" }
