[package]
name = "drogue-device"
version = "0.1.0"
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
license = "Apache-2.0"
description = "An async actor framework for embedded devices"
readme = "README.md"
repository = "https://github.com/drogue-iot/drogue-device"
homepage = "https://blog.drogue.io"
categories = ["embedded", "no-std", "async", "actor"]
keywords = ["async", "embedded", "actor", "no_std"]

[dependencies.heapless]
version = "0.5.6"

[dependencies.cortex-m]
version = "0.6.0"

[dependencies.log]
version = "0.4.13"

[dependencies.embedded-hal]
version = "0.2.4"
features = ["unproven"]

[dependencies.nb]
version = "1.0.0"

[dependencies.stm32l4xx-hal]
version = "0.6.0"
features = ["rt"]
optional = true

[dependencies.nrf52833-hal]
version = "0.12.0"
features = ["rt"]
optional = true

# ----------------------------------------
# embedded_time dependencies
# ----------------------------------------

[dependencies.num]
version = "0.3.0"
default-features = false

[features]
stm32l4xx = [ "stm32l4xx-hal" ]
nrf52833 = [ "nrf52833-hal" ]

