[workspace]
members = [
    "device",
    "apps/wifi",
    "macros",
    "xtask",
]
resolver = "2"

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "5ae276fe50d1445c9f2e8df3871b247f7d59fc0c" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "5ae276fe50d1445c9f2e8df3871b247f7d59fc0c" }
embassy-lora = { git = "https://github.com/embassy-rs/embassy.git", rev = "5ae276fe50d1445c9f2e8df3871b247f7d59fc0c" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "5ae276fe50d1445c9f2e8df3871b247f7d59fc0c" }

# embassy = { path = "../../../../../embassy/embassy" }
# embassy-stm32 = { path = "../../../../../embassy/embassy-stm32" }
# embassy-hal-common = { path = "../../../../../embassy/embassy-hal-common" }
