[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-esp8266"
version = "0.1.0"
description = "BBC micro:bit v2 + ESP8266 WiFi adapter"
keywords = ["networking", "wifi", "esp8266", "microbit", "nrf", "nrf52"]

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

rand_core = { version = "0.6.2", default-features = false }

drogue-device = { path = "../../../../device", features = ["wifi+esp8266", "defmt", "defmt-info"], default-features = false }
drogue-tls = { git = "https://github.com/drogue-iot/drogue-tls.git", rev = "59cb23017f546da8e0f186042758226165400548", default-features = false, features = ["async"], optional = true}
#drogue-tls = { version = "0.2.0", default-features = false, features = ["async"], optional = true}
#drogue-tls = {path = "../../../drogue-tls", default-features = false, optional = true}
wifi-app = { path = "../../../../apps/wifi" }
cortex-m-rt = "0.6"
cortex-m = { version = "0.6", features = ["inline-asm"] }

embassy = { version = "0.1.0", default-features = false, features = ["defmt"] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["defmt", "nrf52833", "time-driver-rtc1", "gpiote"]}
nrf52833-pac = { version = "0.9", features = ["rt"] }
#embassy = {path = "../../../../../../embassy/embassy", default-features = false}
#embassy-nrf = {path = "../../../../../../embassy/embassy-nrf", default-features = false, features = ["nrf52833"]}
cfg-if = "1.0.0"

[features]
default = [
    "defmt-default",
]
tls = ["drogue-tls", "drogue-tls/defmt", "drogue-device/tls"]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
