[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "nucleo-wl55"
version = "0.1.0"
resolver = "2"
description = "STM32 Nucleo-WL55 using LoRaWAN connecting to The Things Network"
keywords = ["lorawan", "lora", "stm32wl", "stm32wl55", "networking", "iot", "stm32"]

[workspace]

[dependencies]
embedded-hal = { version = "0.2.4", features = ["unproven"] }

defmt = "0.2.3"
defmt-rtt = "0.2.0"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }
#panic-halt = "0.2"

drogue-device = { path = "../../../device", features = ["lora+stm32wl", "defmt", "defmt-trace"], default-features = false }
cortex-m-rt = ">=0.6.15,<0.8" #"0.7"
cortex-m = { version = "0.7.3", features = ["inline-asm"] }
heapless = "0.7"
void = { version = "1", default-features = false }
rand_core = { version = "0.6", default-features = false }

embassy = { version = "0.1.0", default-features = false }
embassy-stm32 = { version = "0.1.0", default-features = false, features = ["defmt", "stm32wl55jc_cm4", "time-driver-tim2", "unstable-pac", "subghz"] }

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

[profile.release]
codegen-units = 1
debug = 2
#opt-level = 2
opt-level = "z"
lto = "fat"
debug-assertions = false
incremental = false
overflow-checks = false

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "fb697a265752644d835edce27efbb20d5557b297" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "fb697a265752644d835edce27efbb20d5557b297" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "fb697a265752644d835edce27efbb20d5557b297" }

#embassy = { path = "../../../../../embassy/embassy" }
#embassy-stm32 = { path = "../../../../../embassy/embassy-stm32" }
#embassy-hal-common = { path = "../../../../../embassy/embassy-hal-common" }
