[package]
name = "drogue-device"
version = "0.1.0"
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
license = "Apache-2.0"
description = "An async actor framework for embedded devices"
readme = "README.md"
repository = "https://github.com/drogue-iot/drogue-device"
homepage = "https://blog.drogue.io"
categories = ["embedded", "no-std", "async", "actor"]
keywords = ["async", "embedded", "actor", "no_std"]

[dependencies.heapless]
version = "0.6"

[dependencies.log]
version = "0.4"

[dependencies.generic-array]
version = "0.14"

# ----------------------------------------
# test dependencies
# ----------------------------------------
[dev-dependencies.futures]
version = "0.3"
default-features = false
features = ["executor"]

[dev-dependencies.env_logger]
version = "0.8.2"
