[package]
name = "stm32l4-iot01a"
version = "0.1.0"
authors = ["Bob McWhirter <bmcwhirt@redhat.com>"]
edition = "2018"

[dependencies.drogue-device]
path = "../../../"
features = [
    "chip+stm32l4xx",
    "wifi+eswifi",
]

[dependencies.cortex-m-rt]
version = "0.6"
features = ["device"]

[dependencies.rtt-target]
version = "0.2.2"
features = ["cortex-m"]

[dependencies.panic-rtt-target]
version = "0.1.1"
features = ["cortex-m"]

[dependencies.log]
version = "0.4.11"

[dependencies.rtt-logger]
version = "0.1.0"

[dependencies.stm32l4xx-hal]
version = "0.6.0"
features = ["stm32l4x5", "rt" ]

[dependencies.embedded-hal]
version = "0.2.4"
features = ["unproven"]

[profile.release]
opt-level = "z"
lto = true
