[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nrf9160_xxAA"

rustflags = [
  # Code-size optimizations.
  "-Z", "trap-unreachable=no",
  "-C", "inline-threshold=5",
  "-C", "no-vectorize-loops",
  "-Z", "emit-stack-sizes",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trace"
