[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-ble-temperature"
version = "0.1.0"
description = "BBC micro:bit v2 BLE temperature sensor"
keywords = ["ble", "bluetooth", "microbit", "nrf", "nrf52", "temperature"]

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

drogue-device = { path = "../../../../device", default-features = false, features = ["defmt", "defmt-info"] }

embassy = { version = "0.1.0", default-features = false, features = ["defmt"] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["defmt", "nrf52833", "gpiote", "time-driver-rtc1"]}

cortex-m        = { version = "0.7.2" }
cortex-m-rt = "0.6"
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

# Bluetooth app
ble = { path = "../../../../apps/ble", features = ["withdefmt", "defmt", "defmt-trace", "nrf52833", "s113"] }

[features]
default = [
    "defmt-default",
    "defmt-trace",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
