[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-ble-temperature"
version = "0.1.0"
description = "BBC micro:bit v2 BLE temperature sensor"
keywords = ["ble", "bluetooth", "microbit", "nrf", "nrf52", "temperature"]
resolver = "2"

[workspace]

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

drogue-device = { path = "../../../../device", default-features = false, features = ["defmt", "defmt-info"] }

embassy = { version = "0.1.0", default-features = false, features = ["defmt"] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["defmt", "nrf52833", "gpiote", "time-driver-rtc1"]}

cortex-m        = { version = "0.7.2" }
cortex-m-rt = "0.6"
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

# Bindings for Nordic proprietary softdevice
nrf-softdevice = { version = "0.1.0", git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "71b9e4b3c20ac4fab0d14c4541b365ed48aab58b", features = ["defmt", "defmt-trace", "nrf52833", "s113", "ble-peripheral", "critical-section-impl", "ble-l2cap", "ble-gatt-server"] }
nrf-softdevice-s113 = { version = "0.1.0", git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "71b9e4b3c20ac4fab0d14c4541b365ed48aab58b" }

[features]
default = [
    "defmt-default",
    "defmt-trace",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "d9e2d176256ef4959c1ba60893ea361363d480d3" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "d9e2d176256ef4959c1ba60893ea361363d480d3" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "d9e2d176256ef4959c1ba60893ea361363d480d3" }

#embassy = { path = "../../../../../../embassy/embassy" }
#embassy-nrf = { path = "../../../../../../embassy/embassy-nrf" }
#embassy-hal-common = { path = "../../../../../../embassy/embassy-hal-common" }