[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-ble-temperature"
version = "0.1.0"
description = "BBC micro:bit v2 BLE temperature sensor"
keywords = ["ble", "bluetooth", "microbit", "nrf", "nrf52", "temperature"]
resolver = "2"

[workspace]

[dependencies]
defmt = { version = "0.3" }
panic-probe = { version = "0.3", features = ["print-defmt"], optional = true }
panic-reset = { version = "0.1.1", optional = true }
defmt-rtt = { version = "0.3.2", optional = true }

drogue-device = { path = "../../../../device", default-features = false, features = ["time", "bsp+microbit", "ble+nrf52833"] }

embassy = { version = "0.1.0", default-features = false, features = [] }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52833", "gpiote", "time-driver-rtc1"]}

nrf-softdevice = { version = "0.1.0", features = ["ble-peripheral", "ble-gatt-server", "s113", "nrf52833", "critical-section-impl"] }
nrf-softdevice-s113 = { version = "0.1.0" }

cortex-m        = { version = "0.7" }
cortex-m-rt = "0.6"
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

[features]
default = [
    "panic-reset"
]

debug = [
    "defmt-rtt",
    "panic-probe",
    "drogue-device/defmt",
    "embassy/defmt",
    "embassy-nrf/defmt",
    "drogue-device/defmt",
]

[profile.dev]
codegen-units = 1
debug = 2
debug-assertions = true
incremental = false
opt-level = 3
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = 's'
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[profile.release.build-override]
codegen-units = 8
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "ac3986e40ef297b90de19812aebccfe2e7f9ceec" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "ac3986e40ef297b90de19812aebccfe2e7f9ceec" }
nrf-softdevice = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c584deaf9d9e941f18457934a4a463e078f380ec" }
nrf-softdevice-s113 = { git = "https://github.com/embassy-rs/nrf-softdevice.git", rev = "c584deaf9d9e941f18457934a4a463e078f380ec" }

#embassy = { path = "../../../../../embassy/embassy" }
#embassy-nrf = { path = "../../../../../embassy/embassy-nrf" }
