[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-rak811"
version = "0.1.0"
description = "BBC micro:bit v2 + RAK811 LoRa Adapter with AT command firmware"
keywords = ["networking", "lora", "lorawan", "rak811", "microbit", "nrf", "nrf52"]
resolver = "2"

[workspace]

[dependencies]
panic-probe = { version = "0.2.0", features = ["print-rtt"] }
log = "0.4"
rtt-logger = "0.1"
rtt-target = { version = "0.2.0", features = ["cortex-m"] }

drogue-device = { path = "../../../../device", features = ["lora+rak811"], default-features = false }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }

embassy = { version = "0.1.0", default-features = false }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52833", "time-driver-rtc1", "gpiote"]}

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "b6fc19182b4ae02ea1e9107ca28b88f4a3b0b60a" }
embassy-nrf = { git = "https://github.com/embassy-rs/embassy.git", rev = "b6fc19182b4ae02ea1e9107ca28b88f4a3b0b60a" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "b6fc19182b4ae02ea1e9107ca28b88f4a3b0b60a" }

#embassy = { path = "../../../../../embassy/embassy" }
#embassy-nrf = { path = "../../../../../embassy/embassy-stm32" }
#embassy-hal-common = { path = "../../../../../embassy/embassy-hal-common" }
