[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-rak811"
version = "0.1.0"
description = "BBC micro:bit v2 + RAK811 LoRa Adapter with AT command firmware"
keywords = ["networking", "lora", "lorawan", "rak811", "microbit", "nrf", "nrf52"]

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

drogue-device = { path = "../../../../device", features = ["lora+rak811"], default-features = false }
cortex-m-rt = "0.6"
cortex-m = { version = "0.7", features = ["inline-asm"] }

embassy = { version = "0.1.0", default-features = false }
embassy-nrf = { version = "0.1.0", default-features = false, features = ["nrf52833", "time-driver-rtc1", "gpiote"]}

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
