[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-rak811"
version = "0.1.0"
description = "BBC micro:bit v2 + RAK811 LoRa adapter"
keywords = ["networking", "lora", "lorawan", "rak811", "microbit", "nrf", "nrf52"]

[workspace]

[dependencies]
panic-probe = { version = "0.2.0", features = ["print-rtt"] }
log = "0.4"
rtt-logger = "0.1"
rtt-target = { version = "0.2.0", features = ["cortex-m"] }

drogue-device = { path = "../../../../device", features = ["lora+rak811"], default-features = false }
cortex-m-rt = "0.7"
cortex-m = { version = "0.6", features = ["inline-asm"] }

embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "65bceafa6839b92dd5e4487485f687bdf4b42733", default-features = false}
embassy-nrf = {git = "https://github.com/embassy-rs/embassy.git", rev = "65bceafa6839b92dd5e4487485f687bdf4b42733", default-features = false, features = ["nrf52833", "time-driver-rtc1", "gpiote"]}
#embassy = {path = "../../../../../../embassy/embassy", default-features = false}
#embassy-nrf = {path = "../../../../../../embassy/embassy-nrf", default-features = false, features = ["nrf52833"]}
