[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "wifi-app"
version = "0.1.0"

[workspace]

[dependencies]
drogue-device = { path = "../../../device", features = ["wifi"], default-features = false }
log = "0.4"
heapless = "0.7"
