[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "lora-discovery"
version = "0.1.0"
resolver = "2"
description = "STM32 LoRaWAN Discovery board connecting to The Things Network"
keywords = ["lorawan", "lora", "stm32l0", "networking", "iot", "stm32"]

[workspace]

[dependencies]
embedded-hal = { version = "0.2.4", features = ["unproven"] }
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

drogue-device = { path = "../../../device", features = ["defmt", "defmt-trace", "lora+sx127x"], default-features = false }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = "0.6"
void = { version = "1", default-features = false }
rand_core = { version = "0.6", default-features = false }

embassy = { version = "0.1.0", default-features = false, features = ["time-tick-32768hz"] }
embassy-stm32 = { version = "0.1.0", default-features = false, features = ["stm32l072cz", "time-driver-tim2", "memory-x"] }

[features]

default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]

[profile.release]
codegen-units = 1
debug = 2
opt-level = "s"
lto = "fat"
debug-assertions = false
incremental = false
overflow-checks = false

[patch.crates-io]
embassy = { git = "https://github.com/embassy-rs/embassy.git", rev = "bb72f7eb98ed0431a6b6adf3c59831aed0c4825a" }
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "bb72f7eb98ed0431a6b6adf3c59831aed0c4825a" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "bb72f7eb98ed0431a6b6adf3c59831aed0c4825a" }

# embassy = { path = "../../../../../embassy/embassy" }
# embassy-stm32 = { path = "../../../../../embassy/embassy-stm32" }
# embassy-hal-common = { path = "../../../../../embassy/embassy-hal-common" }