[package]
name = "rp2040-pico-w"
version = "0.1.0"
edition = "2021"
description = "Raspberry Pi Pico W reporting sensor data using WiFi"
keywords = ["wifi", "rpi", "networking", "iot", "picow", "cloud", "ota"]

[workspace]

[dependencies]
cyw43 = { version = "0.1.0", features = ["defmt"] }
embassy-executor = { version = "0.1.0",  features = ["defmt", "integrated-timers"] }
embassy-time = { version = "0.1.0",  features = ["defmt", "defmt-timestamp-uptime"] }
embassy-usb-logger = "0.1.0"
embassy-rp = { version = "0.1.0",  features = ["defmt", "unstable-traits", "nightly", "unstable-pac", "time-driver"] }
embassy-boot-rp = { version = "0.1.0", default-features = false }
embassy-net = { version = "0.1.0", features = ["defmt", "tcp", "dhcpv4", "medium-ethernet", "dns", "unstable-traits", "nightly"] }
drogue-device = { version = "0.1.0", default-features = false }
atomic-polyfill = "0.1.5"
static_cell = "1.0"

defmt = {version = "0.3", optional = true }
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }
reqwless = { version = "0.5", default-features = false, features = ["defmt"] }

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.3"
futures = { version = "0.3.17", default-features = false, features = ["async-await", "cfg-target-has-atomic", "unstable"] }
rand_core = { version = "0.6.2", default-features = false }

embedded-hal-1 = { package = "embedded-hal", version = "1.0.0-alpha.9" }
embedded-hal-async = { version = "0.2.0-alpha.0" }
embedded-io = { version = "0.4.0", features = ["async", "defmt"] }
heapless = "0.7.15"
serde = { version = "=1.0.148", default-features = false, features = ["derive"] }
serde-json-core = { version = "0.4", default-features = false, features = ["heapless"] }
embedded-nal-async = "0.4.0"
rand = { version = "0.8.4", default-features = false }
log = "0.4"

[features]
defmt = ["dep:defmt"]
default = ["defmt"]

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-boot = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-lora = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-boot-rp = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-net = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-net-driver-channel = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-net-driver = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
embassy-usb-logger = { git = "https://github.com/embassy-rs/embassy", rev = "59f706ee2f93252d1c040cea149dfd744f4d8c16" }
cyw43 = { git = "https://github.com/embassy-rs/cyw43.git", rev = "e3492862e994b0c46b23b486cae2935c2c0e05a0"}
drogue-device = { path = "../../../../device" }
