[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "microbit-uart"
version = "0.1.0"
description = "BBC micro:bit v2 uart and matrix display"
keywords = ["uart", "microbit", "nrf", "nrf52", "display"]

[workspace]

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

drogue-device = { path = "../../../../device", default-features = false, features = ["defmt", "defmt-info", "fonts", "time"] }
cortex-m-rt = "0.7"
cortex-m = { version = "0.6", features = ["inline-asm"] }

embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "65bceafa6839b92dd5e4487485f687bdf4b42733", default-features = false}
embassy-nrf = {git = "https://github.com/embassy-rs/embassy.git", rev = "65bceafa6839b92dd5e4487485f687bdf4b42733", default-features = false, features = ["nrf52833", "time-driver-rtc1", "gpiote"]}
#embassy = {path = "../../../../../../embassy/embassy", default-features = false}
#embassy-nrf = {path = "../../../../../../embassy/embassy-nrf", default-features = false, features = ["nrf52833"]}

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
