[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
]
edition = "2018"
name = "ble"
version = "0.1.0"
description = "Bluetooth Low Energy (BLE) GATT services and actors"

[dependencies]
drogue-device = { path = "../../device", default-features = false }
heapless = "0.7"
futures     = { version = "0.3.17", default-features = false, features = ["async-await"] }

embassy = { version = "0.1.0", default-features = false, features = ["time"] }

#nrf-softdevice = { version = "0.1.0", git = "https://github.com/lulf/nrf-softdevice.git", rev = "230d133f4d6e02d2631a3fcdcebe7675764c17fb", features = ["defmt", "defmt-trace", "nrf52833", "s113", "ble-peripheral", "critical-section-impl", "ble-gatt-server"] }
#nrf-softdevice-s113 = { version = "0.1.0", git = "https://github.com/lulf/nrf-softdevice.git", rev = "230d133f4d6e02d2631a3fcdcebe7675764c17fb" }

nrf-softdevice = { version = "0.1.0", path = "../../../../nrf-softdevice/nrf-softdevice", features = ["nrf52833", "s113", "ble-peripheral", "critical-section-impl", "ble-gatt-server"] }
nrf-softdevice-s113 = { version = "0.1.0", path = "../../../../nrf-softdevice/nrf-softdevice-s113" }
