[package]
edition = "2021"
name = "rp-bootloader"
version = "0.1.0"
description = "Bootloader for RP2040 chips"
license = "MIT OR Apache-2.0"
keywords = ["rp2040", "boot"]

[workspace]

[dependencies]
defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.4", optional = true }

embassy-rp = { version = "0.1.0", default-features = false, features = ["nightly"] }
embassy-boot-rp = { version = "0.1.0", default-features = false }
cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7" }
embedded-storage = "0.3.0"
embedded-storage-async = "0.3.0"
cfg-if = "1.0.0"

[features]
defmt = [
    "dep:defmt",
    "embassy-boot-rp/defmt",
    "embassy-rp/defmt",
]
debug = ["defmt-rtt", "defmt"]

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
embassy-boot = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
embassy-boot-rp = { git = "https://github.com/embassy-rs/embassy", rev = "5e94b8060b7f1af8118ca1f943181ce70be92057" }
