[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "hello"
version = "0.1.0"

[workspace]

[dependencies]
log = "0.4"
env_logger = "0.8"
drogue-device = { path = "../../../device", features = ["log", "std"] }
embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "4b74e8fc50b3b1839f118d9b310f793a46adc416", features = ["std"] }
embassy-std = {git = "https://github.com/embassy-rs/embassy.git", rev = "4b74e8fc50b3b1839f118d9b310f793a46adc416", default-features = false }
