[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "esp8266"
version = "0.1.0"
description = "Example using a USB-to-Serial adapter + ESP8266 adapter"
keywords = ["std", "wifi", "networking", "cloud"]

[dependencies]
log = "0.4"
env_logger = "0.8"
drogue-device = { path = "../../../device", features = ["log", "std"] }
esp8266-at-driver = "0.3.0"
embedded-io = "0.6"
embedded-io-async = "0.6"
embedded-io-adapters = { version = "0.6", features = ["std", "futures-03"] }
embedded-nal-async = "0.6"
reqwless = { version = "0.8" }
static_cell = "1"
heapless = "0.7"

embassy-time = { version = "0.1.0", default-features = false, features = ["std"] }
embassy-futures = { version = "0.1.0", default-features = false }
embassy-executor = { version = "0.3", default-features = false, features = ["std", "integrated-timers", "nightly"] }
serde-json-core = { version = "0.4", default-features = false, features = ["heapless", "std"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
rand = "0.8"
cfg-if = "1.0.0"

embedded-hal = { version = "1.0.0-rc.1"}
embedded-hal-async = { version = "1.0.0-rc.1" }

async-io = "1.6.0"
nix = "0.22.1"
futures = { version = "0.3.17" }
libc = "0.2.101"
