[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "nucleo-h743zi_epd"
version = "0.1.0"
description = "STM32 Nucleo-H743 7-color e-paper display"
keywords = ["spi", "stm32h7", "epd", "display"]
resolver = "2"

[workspace]

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

embedded-hal = { version = "0.2.4", features = ["unproven"] }
drogue-device = { path = "../../../../device", features = ["defmt", "defmt-trace"], default-features = false }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = { version = "0.7.1", default-features = false }
void = { version = "1", default-features = false }
embedded-graphics = { version = "0.7.1" }
embedded-graphics-core = { version = "0.3.2" }
epd-waveshare = { git = "https://github.com/Caemor/epd-waveshare.git", features = [ "graphics"] }
tinybmp = "0.3.1"

embassy = {git = "https://github.com/embassy-rs/embassy.git", rev = "bb72f7eb98ed0431a6b6adf3c59831aed0c4825a", default-features = false, features = ["defmt", "defmt-info", "time", "time-tick-32768hz"]}
embassy-stm32 = {git = "https://github.com/embassy-rs/embassy.git", rev = "bb72f7eb98ed0431a6b6adf3c59831aed0c4825a", default-features = false, features = ["stm32h743zi", "defmt", "defmt-info", "memory-x", "time-driver-tim2"] }


[profile.release]
debug = 2
opt-level = "s"
lto = "fat"
