[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "nucleo-h743zi_epd"
version = "0.1.0"
resolver = "2"

[workspace]

[features]
default = [
    "defmt-default",
]
defmt-default = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
defmt = "0.2"
defmt-rtt = "0.2"
panic-probe = { version = "0.2.0", features = ["print-defmt"] }

embedded-hal = { version = "0.2.4", features = ["unproven"] }
drogue-device = { path = "../../../../device", features = ["wifi+esp8266", "defmt", "defmt-trace"], default-features = false }
cortex-m-rt = "0.6"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = "0.6"
void = { version = "1", default-features = false }
embedded-graphics = { version = "0.7.1" }
embedded-graphics-core = { version = "0.3.2" }
epd-waveshare = { git = "https://github.com/Caemor/epd-waveshare.git" }
#epd-waveshare = { path = "/Users/bob/repos/epd-waveshare" }

embassy = {path = "/Users/bob/repos/drogue/embassy/embassy", default-features = false, features = ["defmt", "defmt-info", "time", "time-tick-32768hz"]}
embassy-stm32 = {path = "/Users/bob/repos/drogue/embassy/embassy-stm32", default-features = false, features = ["stm32h743zi", "defmt", "defmt-info", "memory-x", "time-driver-tim2"] }

[profile.release]
debug = 2
opt-level = "s"
lto = "fat"
