name: Build

on:
  push:
    branches: [staging, trying, main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: cache
        id: cache-target
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-device

      - name: Build and test
        run: |
          curl -L -o /usr/local/bin/cargo-batch https://github.com/embassy-rs/cargo-batch/releases/download/batch-0.1.0/cargo-batch
          chmod +x /usr/local/bin/cargo-batch
          cargo xtask ci_batch

      - name: Documentation
        run: cargo xtask docs

      - name: Verify no changes to source modules
        run: git diff --exit-code
